name: my_api_server
description: A Clean Architecture Dart backend server.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^3.5.6
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
